### ISSUE TITLE
iPhone 6+ ipa problem

### ISSUE THREAD

**Issue by mouse1121** [Amcio/UpScale_async_wake#3]
I have iPhone 6 and want to use iPhone 6+ resolution, but when i try to use, i have many lags, and freeze's. Watch: https://youtu.be/g1YdUV2vGkE

Can u help me?

**Comment by Amcio** [comment]
It is a problem with iOS. Many resolutions stopped working correctly  on iOS 11. There’s nothing we can do with it right now.

**Comment by mouse1121** [comment]
@Amcio thank u for answer.
