### ISSUE TITLE
1472×827 on ip7

### ISSUE THREAD

**Issue by YunBiaoWu** [Amcio/UpScale_async_wake#4]
It does not work on iPhone7 
It will change to the default resolution after reboot

**Comment by Amcio** [comment]
That’s interesting... On iPhone 7 changing resolutions is trickier for some reason. Think twice before you change it. It may result in a black screen forcing you to restore or use it QuickTime on Mac to go back to normal resolution. (Its iPhone 6s resolution btw)

**Comment by YunBiaoWu** [comment]
I use default resolution now，but someone suggested to me on reddit try to change to 828 x 1472 and 850 x 1511 on ip7 ,Can you help me to compiled an IPA ，I will test them and report to you，thank you.
